name: Main

on:
  push:

jobs:
  linting:
    uses: ./.github/workflows/linting.yml

  build:
    uses: ./.github/workflows/build.yml
    needs:
      - linting
    with:
      latest: false
      push: true
